// <auto-generated />
using System;
using ErpSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ErpSystemDbContext))]
    [Migration("20260514131856_InitialSystemFoundation")]
    partial class InitialSystemFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Auditing.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionName = "Seeded",
                            ChangedAtUtc = new DateTime(2026, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            EntityId = 1,
                            EntityName = "User",
                            IsDeleted = false,
                            NewValues = "{\"userName\":\"admin\"}",
                            OldValues = "{}",
                            RowVersion = new byte[0],
                            Summary = "Seeded administrator account."
                        },
                        new
                        {
                            Id = 2,
                            ActionName = "Seeded",
                            ChangedAtUtc = new DateTime(2026, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            EntityId = 2,
                            EntityName = "Role",
                            IsDeleted = false,
                            NewValues = "{\"role\":\"WAREHOUSE_MANAGER\"}",
                            OldValues = "{}",
                            RowVersion = new byte[0],
                            Summary = "Seeded warehouse role."
                        },
                        new
                        {
                            Id = 3,
                            ActionName = "Seeded",
                            ChangedAtUtc = new DateTime(2026, 1, 1, 3, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            EntityId = 2,
                            EntityName = "DocumentNumberSequence",
                            IsDeleted = false,
                            NewValues = "{\"key\":\"TRANSPORT_DOMESTIC\"}",
                            OldValues = "{}",
                            RowVersion = new byte[0],
                            Summary = "Seeded domestic transport numbering."
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Dictionaries.DictionaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DictionaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryName", "Code")
                        .IsUnique();

                    b.ToTable("DictionaryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PLN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "Currencies",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Polish zloty",
                            RowVersion = new byte[0],
                            SortOrder = 10,
                            Value = "PLN"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "Currencies",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Euro",
                            RowVersion = new byte[0],
                            SortOrder = 20,
                            Value = "EUR"
                        },
                        new
                        {
                            Id = 3,
                            Code = "TRUCK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "VehicleTypes",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Truck",
                            RowVersion = new byte[0],
                            SortOrder = 10,
                            Value = "Truck"
                        },
                        new
                        {
                            Id = 4,
                            Code = "VAN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "VehicleTypes",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Van",
                            RowVersion = new byte[0],
                            SortOrder = 20,
                            Value = "Van"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ANNUAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "LeaveTypes",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Annual leave",
                            RowVersion = new byte[0],
                            SortOrder = 10,
                            Value = "Annual"
                        },
                        new
                        {
                            Id = 6,
                            Code = "SICK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DictionaryName = "LeaveTypes",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sick leave",
                            RowVersion = new byte[0],
                            SortOrder = 20,
                            Value = "Sick"
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Documents.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerEntityId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "application/pdf",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            FileName = "cmr-scan.pdf",
                            IsDeleted = false,
                            OwnerEntityId = 9001,
                            OwnerEntityName = "TransportOrder",
                            RowVersion = new byte[0],
                            SizeBytes = 245000L,
                            StoragePath = "/attachments/cmr-scan.pdf",
                            UploadedAtUtc = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UploadedByUserId = 3
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "image/jpeg",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            FileName = "goods-photo.jpg",
                            IsDeleted = false,
                            OwnerEntityId = 9002,
                            OwnerEntityName = "WarehouseGoods",
                            RowVersion = new byte[0],
                            SizeBytes = 180250L,
                            StoragePath = "/attachments/goods-photo.jpg",
                            UploadedAtUtc = new DateTime(2026, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            UploadedByUserId = 2
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Documents.DocumentHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("DocumentHistoryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorUserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Transport order created.",
                            DocumentId = 9001,
                            DocumentType = "TransportOrder",
                            EntryType = "Created",
                            IsDeleted = false,
                            OccurredAtUtc = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            StatusCode = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            ActorUserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Driver assigned to the transport order.",
                            DocumentId = 9001,
                            DocumentType = "TransportOrder",
                            EntryType = "Assigned",
                            IsDeleted = false,
                            OccurredAtUtc = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            StatusCode = "Assigned"
                        },
                        new
                        {
                            Id = 3,
                            ActorUserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Goods stock was corrected.",
                            DocumentId = 9002,
                            DocumentType = "WarehouseGoods",
                            EntryType = "Updated",
                            IsDeleted = false,
                            OccurredAtUtc = new DateTime(2026, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            StatusCode = "Active"
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Documents.DocumentNumberSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("LastGeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Padding")
                        .HasColumnType("int");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ResetPolicy")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("DocumentNumberSequences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentNumber = 128,
                            IsDeleted = false,
                            Key = "WAREHOUSE_GOODS",
                            LastGeneratedAtUtc = new DateTime(2026, 5, 14, 13, 18, 55, 988, DateTimeKind.Utc).AddTicks(1250),
                            Padding = 5,
                            Prefix = "WG",
                            ResetPolicy = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentNumber = 42,
                            IsDeleted = false,
                            Key = "TRANSPORT_DOMESTIC",
                            LastGeneratedAtUtc = new DateTime(2026, 5, 14, 13, 18, 55, 988, DateTimeKind.Utc).AddTicks(1330),
                            Padding = 5,
                            Prefix = "TD",
                            ResetPolicy = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentNumber = 9,
                            IsDeleted = false,
                            Key = "TRANSPORT_INTERNATIONAL",
                            LastGeneratedAtUtc = new DateTime(2026, 5, 14, 13, 18, 55, 988, DateTimeKind.Utc).AddTicks(1330),
                            Padding = 5,
                            Prefix = "TI",
                            ResetPolicy = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            CurrentNumber = 15,
                            IsDeleted = false,
                            Key = "HR_EMPLOYEE",
                            LastGeneratedAtUtc = new DateTime(2026, 5, 14, 13, 18, 55, 988, DateTimeKind.Utc).AddTicks(1330),
                            Padding = 4,
                            Prefix = "HE",
                            ResetPolicy = 0,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Documents.DocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey", "Code")
                        .IsUnique();

                    b.ToTable("DocumentStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = false,
                            ModuleKey = "warehouse",
                            Name = "Active",
                            RowVersion = new byte[0],
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            Code = "Archived",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = true,
                            ModuleKey = "warehouse",
                            Name = "Archived",
                            RowVersion = new byte[0],
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            Code = "Draft",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = false,
                            ModuleKey = "transport",
                            Name = "Draft",
                            RowVersion = new byte[0],
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 4,
                            Code = "Assigned",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = false,
                            ModuleKey = "transport",
                            Name = "Assigned",
                            RowVersion = new byte[0],
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 5,
                            Code = "Completed",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = true,
                            ModuleKey = "transport",
                            Name = "Completed",
                            RowVersion = new byte[0],
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 6,
                            Code = "Requested",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = false,
                            ModuleKey = "hr",
                            Name = "Requested",
                            RowVersion = new byte[0],
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 7,
                            Code = "Approved",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = true,
                            ModuleKey = "hr",
                            Name = "Approved",
                            RowVersion = new byte[0],
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 8,
                            Code = "Rejected",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            IsTerminal = true,
                            ModuleKey = "hr",
                            Name = "Rejected",
                            RowVersion = new byte[0],
                            SortOrder = 30
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read system users.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Users.Read",
                            Resource = "Users",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Create system users.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Users.Create",
                            Resource = "Users",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Action = "Edit",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Edit system users.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Users.Edit",
                            Resource = "Users",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Delete system users.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Users.Delete",
                            Resource = "Users",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read role definitions.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Roles.Read",
                            Resource = "Roles",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            Action = "Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Manage roles.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Roles.Manage",
                            Resource = "Roles",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 7,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read permissions.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Permissions.Read",
                            Resource = "Permissions",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 8,
                            Action = "Assign",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Assign permissions to roles.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Permissions.Assign",
                            Resource = "Permissions",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 9,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read application menu.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Menu.Read",
                            Resource = "Menu",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 10,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read audit logs.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Audit.Read",
                            Resource = "Audit",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 11,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read dictionary items.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Dictionaries.Read",
                            Resource = "Dictionaries",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 12,
                            Action = "Manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Manage dictionary items.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Dictionaries.Manage",
                            Resource = "Dictionaries",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 13,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read attachments.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Attachments.Read",
                            Resource = "Attachments",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 14,
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Add attachments.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Attachments.Create",
                            Resource = "Attachments",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 15,
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Delete attachments.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.Attachments.Delete",
                            Resource = "Attachments",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 16,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read document history.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.DocumentHistory.Read",
                            Resource = "DocumentHistory",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 17,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read document sequences.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.DocumentNumbers.Read",
                            Resource = "DocumentNumbers",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 18,
                            Action = "Generate",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Generate next document number.",
                            IsDeleted = false,
                            ModuleKey = "system",
                            Name = "System.DocumentNumbers.Generate",
                            Resource = "DocumentNumbers",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 19,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read warehouse goods.",
                            IsDeleted = false,
                            ModuleKey = "warehouse",
                            Name = "Warehouse.Goods.Read",
                            Resource = "Goods",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 20,
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Create warehouse goods.",
                            IsDeleted = false,
                            ModuleKey = "warehouse",
                            Name = "Warehouse.Goods.Create",
                            Resource = "Goods",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 21,
                            Action = "Edit",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Edit warehouse goods.",
                            IsDeleted = false,
                            ModuleKey = "warehouse",
                            Name = "Warehouse.Goods.Edit",
                            Resource = "Goods",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 22,
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Delete warehouse goods.",
                            IsDeleted = false,
                            ModuleKey = "warehouse",
                            Name = "Warehouse.Goods.Delete",
                            Resource = "Goods",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 23,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read transport orders.",
                            IsDeleted = false,
                            ModuleKey = "transport",
                            Name = "Transport.Order.Read",
                            Resource = "Order",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 24,
                            Action = "Create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Create transport orders.",
                            IsDeleted = false,
                            ModuleKey = "transport",
                            Name = "Transport.Order.Create",
                            Resource = "Order",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 25,
                            Action = "ChangeStatus",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Change transport order status.",
                            IsDeleted = false,
                            ModuleKey = "transport",
                            Name = "Transport.Order.ChangeStatus",
                            Resource = "Order",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 26,
                            Action = "AssignDriver",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Assign driver to transport order.",
                            IsDeleted = false,
                            ModuleKey = "transport",
                            Name = "Transport.Order.AssignDriver",
                            Resource = "Order",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 27,
                            Action = "Read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Read employee cards.",
                            IsDeleted = false,
                            ModuleKey = "hr",
                            Name = "HR.Employee.Read",
                            Resource = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 28,
                            Action = "Edit",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Edit employee cards.",
                            IsDeleted = false,
                            ModuleKey = "hr",
                            Name = "HR.Employee.Edit",
                            Resource = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 29,
                            Action = "Approve",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Approve leave requests.",
                            IsDeleted = false,
                            ModuleKey = "hr",
                            Name = "HR.Leave.Approve",
                            Resource = "Leave",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SYSTEM_ADMIN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Full access to the ERP foundation.",
                            IsDeleted = false,
                            IsSystem = true,
                            Name = "System administrator",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            Code = "WAREHOUSE_MANAGER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Warehouse operations and goods maintenance.",
                            IsDeleted = false,
                            IsSystem = false,
                            Name = "Warehouse manager",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            Code = "TRANSPORT_DISPATCHER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Transport orders and dispatch operations.",
                            IsDeleted = false,
                            IsSystem = false,
                            Name = "Transport dispatcher",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            Code = "HR_MANAGER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Employee records and leave approvals.",
                            IsDeleted = false,
                            IsSystem = false,
                            Name = "HR manager",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 1,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 2,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 3,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 4,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 5,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 6,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 7,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 8,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 10,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 11,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 12,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 15,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 17,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 21,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 23,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 26,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 27,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 28,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 29,
                            RoleId = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 17,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 18,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 19,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 20,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 21,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 22,
                            RoleId = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 13,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 14,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 23,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 24,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 25,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 26,
                            RoleId = 3,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 9,
                            RoleId = 4,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 16,
                            RoleId = 4,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 27,
                            RoleId = 4,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 28,
                            RoleId = 4,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            PermissionId = 29,
                            RoleId = 4,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DisplayName = "System Administrator",
                            Email = "admin@erpsystem.local",
                            IsActive = true,
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DisplayName = "Warehouse Manager",
                            Email = "warehouse@erpsystem.local",
                            IsActive = true,
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            UserName = "warehouse"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DisplayName = "Transport Dispatcher",
                            Email = "transport@erpsystem.local",
                            IsActive = true,
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            UserName = "transport"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            DisplayName = "HR Manager",
                            Email = "hr@erpsystem.local",
                            IsActive = true,
                            IsDeleted = false,
                            RowVersion = new byte[0],
                            UserName = "hr"
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            RoleId = 1,
                            RowVersion = new byte[0],
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            RoleId = 2,
                            RowVersion = new byte[0],
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            RoleId = 3,
                            RowVersion = new byte[0],
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            IsDeleted = false,
                            RoleId = 4,
                            RowVersion = new byte[0],
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.RolePermission", b =>
                {
                    b.HasOne("ErpSystem.Domain.Modules.System.Identity.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpSystem.Domain.Modules.System.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpSystem.Domain.Modules.System.Identity.UserRole", b =>
                {
                    b.HasOne("ErpSystem.Domain.Modules.System.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpSystem.Domain.Modules.System.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
