namespace ErpSystem.Shared.Security;

public static class PermissionCatalog
{
    public static IReadOnlyList<PermissionDefinition> All { get; } =
    [
        new(PermissionNames.System.Users.Read, "system", "Users", "Read", "Read system users."),
        new(PermissionNames.System.Users.Create, "system", "Users", "Create", "Create system users."),
        new(PermissionNames.System.Users.Edit, "system", "Users", "Edit", "Edit system users."),
        new(PermissionNames.System.Users.Delete, "system", "Users", "Delete", "Delete system users."),
        new(PermissionNames.System.Roles.Read, "system", "Roles", "Read", "Read role definitions."),
        new(PermissionNames.System.Roles.Manage, "system", "Roles", "Manage", "Manage roles."),
        new(PermissionNames.System.Permissions.Read, "system", "Permissions", "Read", "Read permissions."),
        new(PermissionNames.System.Permissions.Assign, "system", "Permissions", "Assign", "Assign permissions to roles."),
        new(PermissionNames.System.Menu.Read, "system", "Menu", "Read", "Read application menu."),
        new(PermissionNames.System.Audit.Read, "system", "Audit", "Read", "Read audit logs."),
        new(PermissionNames.System.Dictionaries.Read, "system", "Dictionaries", "Read", "Read dictionary items."),
        new(PermissionNames.System.Dictionaries.Manage, "system", "Dictionaries", "Manage", "Manage dictionary items."),
        new(PermissionNames.System.Attachments.Read, "system", "Attachments", "Read", "Read attachments."),
        new(PermissionNames.System.Attachments.Create, "system", "Attachments", "Create", "Add attachments."),
        new(PermissionNames.System.Attachments.Delete, "system", "Attachments", "Delete", "Delete attachments."),
        new(PermissionNames.System.DocumentHistory.Read, "system", "DocumentHistory", "Read", "Read document history."),
        new(PermissionNames.System.DocumentNumbers.Read, "system", "DocumentNumbers", "Read", "Read document sequences."),
        new(PermissionNames.System.DocumentNumbers.Generate, "system", "DocumentNumbers", "Generate", "Generate next document number."),
        new(PermissionNames.Contractors.Contractor.Read, "contractors", "Contractor", "Read", "Read contractors."),
        new(PermissionNames.Contractors.Contractor.Create, "contractors", "Contractor", "Create", "Create contractors."),
        new(PermissionNames.Contractors.Contractor.Edit, "contractors", "Contractor", "Edit", "Edit contractors."),
        new(PermissionNames.Contractors.Contractor.ChangeStatus, "contractors", "Contractor", "ChangeStatus", "Change contractor activity status."),
        new(PermissionNames.Contractors.Contractor.ViewHistory, "contractors", "Contractor", "ViewHistory", "Read contractor change history."),
        new(PermissionNames.Warehouse.Goods.Read, "warehouse", "Goods", "Read", "Read warehouse goods."),
        new(PermissionNames.Warehouse.Goods.Create, "warehouse", "Goods", "Create", "Create warehouse goods."),
        new(PermissionNames.Warehouse.Goods.Edit, "warehouse", "Goods", "Edit", "Edit warehouse goods."),
        new(PermissionNames.Warehouse.Goods.Delete, "warehouse", "Goods", "Delete", "Delete warehouse goods."),
        new(PermissionNames.Warehouse.Documents.Read, "warehouse", "Documents", "Read", "Read warehouse documents."),
        new(PermissionNames.Warehouse.Documents.Create, "warehouse", "Documents", "Create", "Create draft warehouse documents."),
        new(PermissionNames.Warehouse.Documents.Post, "warehouse", "Documents", "Post", "Post warehouse documents and generate stock movements."),
        new(PermissionNames.Warehouse.Stock.Read, "warehouse", "Stock", "Read", "Read current warehouse stock."),
        new(PermissionNames.Transport.Order.Read, "transport", "Order", "Read", "Read transport orders."),
        new(PermissionNames.Transport.Order.Create, "transport", "Order", "Create", "Create transport orders."),
        new(PermissionNames.Transport.Order.Edit, "transport", "Order", "Edit", "Edit transport orders."),
        new(PermissionNames.Transport.Order.ChangeStatus, "transport", "Order", "ChangeStatus", "Change transport order status."),
        new(PermissionNames.Transport.Order.AssignDriver, "transport", "Order", "AssignDriver", "Assign driver to transport order."),
        new(PermissionNames.HR.Employee.Read, "hr", "Employee", "Read", "Read employee cards."),
        new(PermissionNames.HR.Employee.Create, "hr", "Employee", "Create", "Create employee cards."),
        new(PermissionNames.HR.Employee.Edit, "hr", "Employee", "Edit", "Edit employee cards."),
        new(PermissionNames.HR.Department.Read, "hr", "Department", "Read", "Read departments."),
        new(PermissionNames.HR.Department.Manage, "hr", "Department", "Manage", "Manage departments."),
        new(PermissionNames.HR.Position.Read, "hr", "Position", "Read", "Read positions."),
        new(PermissionNames.HR.Position.Manage, "hr", "Position", "Manage", "Manage positions."),
        new(PermissionNames.HR.Contract.Read, "hr", "Contract", "Read", "Read employment contracts."),
        new(PermissionNames.HR.Contract.Manage, "hr", "Contract", "Manage", "Manage employment contracts."),
        new(PermissionNames.HR.Leave.Read, "hr", "Leave", "Read", "Read leave requests."),
        new(PermissionNames.HR.Leave.Create, "hr", "Leave", "Create", "Create leave requests."),
        new(PermissionNames.HR.Leave.Approve, "hr", "Leave", "Approve", "Approve leave requests.")
        ,
        new(PermissionNames.HR.Schedule.Read, "hr", "Schedule", "Read", "Read work schedules."),
        new(PermissionNames.HR.Schedule.Manage, "hr", "Schedule", "Manage", "Manage work schedules."),
        new(PermissionNames.HR.Document.Read, "hr", "Document", "Read", "Read employee documents."),
        new(PermissionNames.HR.Document.Manage, "hr", "Document", "Manage", "Manage employee documents."),
        new(PermissionNames.Finance.Cost.Read, "finance", "Cost", "Read", "Read cost documents."),
        new(PermissionNames.Finance.Cost.Create, "finance", "Cost", "Create", "Create cost documents."),
        new(PermissionNames.Finance.Cost.Edit, "finance", "Cost", "Edit", "Edit cost documents."),
        new(PermissionNames.Finance.Invoice.Read, "finance", "Invoice", "Read", "Read invoices."),
        new(PermissionNames.Finance.Invoice.Create, "finance", "Invoice", "Create", "Create invoices."),
        new(PermissionNames.Finance.Invoice.Edit, "finance", "Invoice", "Edit", "Edit invoices."),
        new(PermissionNames.Finance.Payment.Read, "finance", "Payment", "Read", "Read payments."),
        new(PermissionNames.Finance.Payment.Create, "finance", "Payment", "Create", "Create payments."),
        new(PermissionNames.Finance.CurrencyRate.Read, "finance", "CurrencyRate", "Read", "Read currency rates."),
        new(PermissionNames.Finance.CurrencyRate.Manage, "finance", "CurrencyRate", "Manage", "Manage currency rates."),
        new(PermissionNames.Finance.Settlement.Read, "finance", "Settlement", "Read", "Read settlements."),
        new(PermissionNames.Finance.Settlement.Manage, "finance", "Settlement", "Manage", "Manage settlements.")
    ];
}
